language: java
jdk:
  - openjdk8

env:
  global:
    - BUILD_TAG=${TRAVIS_COMMIT::8}-$TRAVIS_BUILD_NUMBER\
    - DEPLOY_FILENAME=book-and-author_$BUILD_TAG.zip

branches:
  only:
    - master

before_install:
  - chmod +x mvnw

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle

script:
  - ./mvnw clean package -DskipTests

before_deploy:
  - mkdir -p deploy_files
  - cp scripts/*.sh deploy_files/
  - cp appspec.yml deploy_files/
  - cp target/*.jar deploy_files/book-and-author.jar
  - zip -j book-and-author.zip deploy_files/*
  - mkdir -p deploy
  - cp book-and-author.zip deploy/

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: jfreshik-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: jfreshik-build
    key: book-and-author.zip
    application: book-and-author-graphql
    deployment_group: jfreshik-deploy-group
    region: ap-northeast-2
