language: java
jdk:
  - openjdk8

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

branches:
  only:
    - master

before_install:
  - chmod +x mvnw

cache:
  - directories:
      - '$HOME/.m2'
      - '$HOME/.gradle'


script: "./mvnw clean package"

before_deploy:
  - export BUILD_TAG=$COMMIT-$TRAVIS_BUILD_NUMBER
  - zip -r book-and-author *
  - mkdir -p deploy
  - mv book-and-author.zip deploy/book-and-author_$BUILD_TAG.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: jfreshik-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true